Update Equibop module
Equibop: Update bun-linux-x64.zip to 1.3.3
Equibop: Update bun-linux-aarch64.zip to 1.3.3

diff --git a/org.equicord.equibop.yml b/org.equicord.equibop.yml
--- a/org.equicord.equibop.yml
+++ b/org.equicord.equibop.yml
@@ -7,161 +7,158 @@ sdk: org.freedesktop.Sdk
 base: org.electronjs.Electron2.BaseApp
 base-version: *runtime-version
 sdk-extensions:
-    - org.freedesktop.Sdk.Extension.node20
+  - org.freedesktop.Sdk.Extension.node20
 
 command: startequibop
 separate-locales: false
 
 finish-args:
-    - --socket=pulseaudio
-    - --socket=fallback-x11
-    - --socket=wayland
-    - --share=ipc
-    - --share=network
-    - --own-name=org.equicord.equibop.StatusNotifierItem # Needed for libvesktop native tray
-    - --talk-name=com.canonical.AppMenu.Registrar
-    - --device=all # Needed for GPU acceleration and the webcam
-    - --filesystem=xdg-videos:ro
-    - --filesystem=xdg-pictures:ro
-    - --filesystem=xdg-download # This and the above two are used for drag-n-drop, and download managing
-    - --filesystem=xdg-run/pipewire-0:ro # Pipewire interfacing
-    - --filesystem=xdg-run/speech-dispatcher:ro # For TTS and VcNarrator
-    - --filesystem=~/.steam # Needed for SteamOS integration, as the XDG OpenURL portal doesn't work properly in Game Mode. We only need ~/.steam/steam.pipe but Flatpak can't correctly mount just that: 'File "/home/deck/.steam/steam.pipe" has unsupported type 0o10000'
-    - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons # This is used to show the correct cursor on Wayland
+  - --socket=pulseaudio
+  - --socket=fallback-x11
+  - --socket=wayland
+  - --share=ipc
+  - --share=network
+  - --own-name=org.equicord.equibop.StatusNotifierItem   # Needed for libvesktop native tray
+  - --talk-name=com.canonical.AppMenu.Registrar
+  - --device=all   # Needed for GPU acceleration and the webcam
+  - --filesystem=xdg-videos:ro
+  - --filesystem=xdg-pictures:ro
+  - --filesystem=xdg-download   # This and the above two are used for drag-n-drop, and download managing
+  - --filesystem=xdg-run/pipewire-0:ro   # Pipewire interfacing
+  - --filesystem=xdg-run/speech-dispatcher:ro   # For TTS and VcNarrator
+  - --filesystem=~/.steam   # Needed for SteamOS integration, as the XDG OpenURL portal doesn't work properly in Game Mode. We only need ~/.steam/steam.pipe but Flatpak can't correctly mount just that: 'File "/home/deck/.steam/steam.pipe" has unsupported type 0o10000'
+  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons   # This is used to show the correct cursor on Wayland
 
 modules:
-    - name: Equibop
-      buildsystem: simple
-      build-options:
-          strip: false
-          no-debuginfo: true
-      build-commands:
-          - tar xzf node_modules.tar.gz
+  - name: Equibop
+    buildsystem: simple
+    build-options:
+      strip: false
+      no-debuginfo: true
+    build-commands:
+      - tar xzf node_modules.tar.gz
 
-          - bun-build/bun run build
+      - bun-build/bun run build
 
-          - export PATH="$PWD/bun-build:$PATH" && . /usr/lib/sdk/node20/enable.sh && node_modules/.bin/electron-builder --dir --linux dir --config.electronDist=node_modules/electron/dist
+      - export PATH="$PWD/bun-build:$PATH" && . /usr/lib/sdk/node20/enable.sh && node_modules/.bin/electron-builder
+        --dir --linux dir --config.electronDist=node_modules/electron/dist
 
-          - |
-              if [ -d 'dist/linux-unpacked' ]; then
-                DIST_DIR='dist/linux-unpacked'
-              elif [ -d 'dist/linux-arm64-unpacked' ]; then
-                DIST_DIR='dist/linux-arm64-unpacked'
-              else
-                echo 'Error: Could not find unpacked directory'
-                exit 1
-              fi
+      - |
+        if [ -d 'dist/linux-unpacked' ]; then
+          DIST_DIR='dist/linux-unpacked'
+        elif [ -d 'dist/linux-arm64-unpacked' ]; then
+          DIST_DIR='dist/linux-arm64-unpacked'
+        else
+          echo 'Error: Could not find unpacked directory'
+          exit 1
+        fi
 
-              mkdir -p "$DIST_DIR/resources/app.asar.unpacked/static/dist"
-              if [ "$FLATPAK_ARCH" = 'x86_64' ]; then
-                  cp arrpc-bun-linux-x64 "$DIST_DIR/resources/app.asar.unpacked/static/dist/arrpc-linux-x64"
-              elif [ "$FLATPAK_ARCH" = 'aarch64' ]; then
-                  cp arrpc-bun-linux-arm64 "$DIST_DIR/resources/app.asar.unpacked/static/dist/arrpc-linux-arm64"
-              fi
-              chmod +x "$DIST_DIR/resources/app.asar.unpacked/static/dist/arrpc-"*
+        mkdir -p "$DIST_DIR/resources/app.asar.unpacked/static/dist"
+        if [ "$FLATPAK_ARCH" = 'x86_64' ]; then
+            cp arrpc-bun-linux-x64 "$DIST_DIR/resources/app.asar.unpacked/static/dist/arrpc-linux-x64"
+        elif [ "$FLATPAK_ARCH" = 'aarch64' ]; then
+            cp arrpc-bun-linux-arm64 "$DIST_DIR/resources/app.asar.unpacked/static/dist/arrpc-linux-arm64"
+        fi
+        chmod +x "$DIST_DIR/resources/app.asar.unpacked/static/dist/arrpc-"*
 
-              install -Dm644 build/icon.svg /app/share/icons/hicolor/scalable/apps/org.equicord.equibop.svg
+        install -Dm644 build/icon.svg /app/share/icons/hicolor/scalable/apps/org.equicord.equibop.svg
 
-              desktop-file-edit --set-key=Exec --set-value='startequibop %U' build/org.equicord.equibop.desktop
-              install -Dm644 build/org.equicord.equibop.desktop /app/share/applications/org.equicord.equibop.desktop
-              install -Dm755 startequibop /app/bin/startequibop
-              install -D build/org.equicord.equibop.metainfo.xml -t /app/share/metainfo/
+        desktop-file-edit --set-key=Exec --set-value='startequibop %U' build/org.equicord.equibop.desktop
+        install -Dm644 build/org.equicord.equibop.desktop /app/share/applications/org.equicord.equibop.desktop
+        install -Dm755 startequibop /app/bin/startequibop
+        install -D build/org.equicord.equibop.metainfo.xml -t /app/share/metainfo/
 
-              cp --reflink=auto -r "$DIST_DIR" /app/bin/equibop
+        cp --reflink=auto -r "$DIST_DIR" /app/bin/equibop
 
-      sources:
-          - type: file
-            path: startequibop
+    sources:
+      - type: file
+        path: startequibop
 
-          - type: archive
-            url: https://api.github.com/repos/Equicord/Equibop/tarball/v3.1.3
-            dest-filename: equibop-v3.1.3.tar.gz
-            sha512: 1dd2329788ef12f9d00ff2ec93eb5964a8f9420c2230e20a15356b4d5ead4e80904bdb3c6ff47f2a59a365f435f6e560e618fd153418c7c0759b219c7f829f1c
-            strip-components: 1
-            x-checker-data:
-                type: json
-                url: https://api.github.com/repos/Equicord/Equibop/releases/latest
-                version-query: .tag_name | sub("v"; "")
-                url-query: .tarball_url
-                is-main-source: true
+      - type: archive
+        url: https://api.github.com/repos/Equicord/Equibop/tarball/v3.1.3
+        dest-filename: equibop-v3.1.3.tar.gz
+        sha512: 1dd2329788ef12f9d00ff2ec93eb5964a8f9420c2230e20a15356b4d5ead4e80904bdb3c6ff47f2a59a365f435f6e560e618fd153418c7c0759b219c7f829f1c
+        strip-components: 1
+        x-checker-data:
+          type: json
+          url: https://api.github.com/repos/Equicord/Equibop/releases/latest
+          version-query: .tag_name | sub("v"; "")
+          url-query: .tarball_url
+          is-main-source: true
 
-          - type: patch
-            path: sandboxFix.patch
+      - type: patch
+        path: sandboxFix.patch
 
-          - type: patch
-            path: gitHash.patch
+      - type: patch
+        path: gitHash.patch
 
-          - type: patch
-            path: arrpcPath.patch
+      - type: patch
+        path: arrpcPath.patch
 
-          - type: file
-            url: https://github.com/Equicord/Equibop/releases/download/v3.1.3/node_modules-x64.tar.gz
-            dest-filename: node_modules.tar.gz
-            sha512: 814b6248cbacde87117bbf5b27aaf054f67ca75277eb8f2b18d6209bcb7595a49bf6eae7910b3f80388b4a5aed596f1562b3712b6243d03bff4df10aa86d61d6
-            only-arches: [x86_64]
-            x-checker-data:
-                type: json
-                url: https://api.github.com/repos/Equicord/Equibop/releases/latest
-                version-query: .tag_name | sub("v"; "")
-                url-query:
-                    .assets[] | select(.name == "node_modules-x64.tar.gz")
-                    | .browser_download_url
+      - type: file
+        url: https://github.com/Equicord/Equibop/releases/download/v3.1.3/node_modules-x64.tar.gz
+        dest-filename: node_modules.tar.gz
+        sha512: 814b6248cbacde87117bbf5b27aaf054f67ca75277eb8f2b18d6209bcb7595a49bf6eae7910b3f80388b4a5aed596f1562b3712b6243d03bff4df10aa86d61d6
+        only-arches: [x86_64]
+        x-checker-data:
+          type: json
+          url: https://api.github.com/repos/Equicord/Equibop/releases/latest
+          version-query: .tag_name | sub("v"; "")
+          url-query: .assets[] | select(.name == "node_modules-x64.tar.gz") | .browser_download_url
 
-          - type: file
-            url: https://github.com/Equicord/Equibop/releases/download/v3.1.3/node_modules-arm64.tar.gz
-            dest-filename: node_modules.tar.gz
-            sha512: 6d55b654e65ab8a6dea9c51121fa117cc7bc33886230d9deebf8fa6b0c4792d02c9812d30bf735a492e69ad9a2be1fde1e6ca487b284d2db71a53624a42de370
-            only-arches: [aarch64]
-            x-checker-data:
-                type: json
-                url: https://api.github.com/repos/Equicord/Equibop/releases/latest
-                version-query: .tag_name | sub("v"; "")
-                url-query:
-                    .assets[] | select(.name == "node_modules-arm64.tar.gz")
-                    | .browser_download_url
+      - type: file
+        url: https://github.com/Equicord/Equibop/releases/download/v3.1.3/node_modules-arm64.tar.gz
+        dest-filename: node_modules.tar.gz
+        sha512: 6d55b654e65ab8a6dea9c51121fa117cc7bc33886230d9deebf8fa6b0c4792d02c9812d30bf735a492e69ad9a2be1fde1e6ca487b284d2db71a53624a42de370
+        only-arches: [aarch64]
+        x-checker-data:
+          type: json
+          url: https://api.github.com/repos/Equicord/Equibop/releases/latest
+          version-query: .tag_name | sub("v"; "")
+          url-query: .assets[] | select(.name == "node_modules-arm64.tar.gz") | .browser_download_url
 
-          - type: archive
-            url: https://github.com/electron/electron/releases/download/v39.2.1/electron-v39.2.1-linux-x64.zip
-            sha512: aa22f877c482ec3be3a59545894dda78370a7b62535eb3571475cc76b41fc4a2799208ae6d9637de1302c954b8a1a020534c996a1f1de0954d52375d72414a90
-            dest: node_modules/electron/dist
-            only-arches: [x86_64]
+      - type: archive
+        url: https://github.com/electron/electron/releases/download/v39.2.1/electron-v39.2.1-linux-x64.zip
+        sha512: aa22f877c482ec3be3a59545894dda78370a7b62535eb3571475cc76b41fc4a2799208ae6d9637de1302c954b8a1a020534c996a1f1de0954d52375d72414a90
+        dest: node_modules/electron/dist
+        only-arches: [x86_64]
 
-          - type: archive
-            url: https://github.com/electron/electron/releases/download/v39.2.1/electron-v39.2.1-linux-arm64.zip
-            sha512: 5e56357a3be7a9ec93e337531260f9277cd3275e63135de665c6317b7ac53b489c316e83512efe72477c4da03bb2c5eb9ce29a7ae7de4d9665cc612477ce5148
-            dest: node_modules/electron/dist
-            only-arches: [aarch64]
+      - type: archive
+        url: https://github.com/electron/electron/releases/download/v39.2.1/electron-v39.2.1-linux-arm64.zip
+        sha512: 5e56357a3be7a9ec93e337531260f9277cd3275e63135de665c6317b7ac53b489c316e83512efe72477c4da03bb2c5eb9ce29a7ae7de4d9665cc612477ce5148
+        dest: node_modules/electron/dist
+        only-arches: [aarch64]
 
-          - type: archive
-            url: https://github.com/oven-sh/bun/releases/download/bun-v1.3.2/bun-linux-x64.zip
-            sha512: 9b33415f60066037c9d4e4afe58612f1e1ba826dc8d21e4d959b553c9dd71ae301c5c6646afdb77ae83ec7ca057d3ed6625fe347d74badc30c487735f9a1d8cb
-            dest: bun-build
-            only-arches: [x86_64]
-            x-checker-data:
-                type: json
-                url: https://api.github.com/repos/oven-sh/bun/releases/latest
-                version-query: .tag_name | sub("bun-v"; "")
-                url-query: .assets[] | select(.name == "bun-linux-x64.zip") | .browser_download_url
+      - type: archive
+        url: https://github.com/oven-sh/bun/releases/download/bun-v1.3.3/bun-linux-x64.zip
+        sha512: cfc496cfa149fddabfe799ee0c492d3f5499746a0b67ce720ef8b0fd9f7cf42ef27afa05a00a1ed5936e1f100586e0d966c4cce33ef9a8b7f588df6ca1cf52e9
+        dest: bun-build
+        only-arches: [x86_64]
+        x-checker-data:
+          type: json
+          url: https://api.github.com/repos/oven-sh/bun/releases/latest
+          version-query: .tag_name | sub("bun-v"; "")
+          url-query: .assets[] | select(.name == "bun-linux-x64.zip") | .browser_download_url
 
-          - type: archive
-            url: https://github.com/oven-sh/bun/releases/download/bun-v1.3.2/bun-linux-aarch64.zip
-            sha512: c9faa81ff20e4365081d7bac1d7ec6677d4e912d7ad69f885532dd43cdf150f495ce8fd152b8218bff716adc1a026fb10948b74e9e1b7d82c7ae7c467fc59a8a
-            dest: bun-build
-            only-arches: [aarch64]
-            x-checker-data:
-                type: json
-                url: https://api.github.com/repos/oven-sh/bun/releases/latest
-                version-query: .tag_name | sub("bun-v"; "")
-                url-query: .assets[] | select(.name == "bun-linux-aarch64.zip") | .browser_download_url
+      - type: archive
+        url: https://github.com/oven-sh/bun/releases/download/bun-v1.3.3/bun-linux-aarch64.zip
+        sha512: ec0aabbf47c88870a6bb95f5a0f074cb61d15bd59c09837ac05eb5e78bb5c7717c9e9d91eaaa03f511c8947ea4be2033dfe1333d85e349134f9567336efe4b76
+        dest: bun-build
+        only-arches: [aarch64]
+        x-checker-data:
+          type: json
+          url: https://api.github.com/repos/oven-sh/bun/releases/latest
+          version-query: .tag_name | sub("bun-v"; "")
+          url-query: .assets[] | select(.name == "bun-linux-aarch64.zip") | .browser_download_url
 
-          - type: file
-            url: https://github.com/Creationsss/arrpc-bun/releases/download/v1.3.1/arrpc-bun-linux-x64
-            sha512: b7082e7b77937b38ddf3a2f99068ddbe3e6e7f1953a2ff881c0d729be009b3560d0ef71cb11089ae068ad8b52048c232b661730c955b31f85d96316ca35f7389
-            dest-filename: arrpc-bun-linux-x64
-            only-arches: [x86_64]
+      - type: file
+        url: https://github.com/Creationsss/arrpc-bun/releases/download/v1.3.1/arrpc-bun-linux-x64
+        sha512: b7082e7b77937b38ddf3a2f99068ddbe3e6e7f1953a2ff881c0d729be009b3560d0ef71cb11089ae068ad8b52048c232b661730c955b31f85d96316ca35f7389
+        dest-filename: arrpc-bun-linux-x64
+        only-arches: [x86_64]
 
-          - type: file
-            url: https://github.com/Creationsss/arrpc-bun/releases/download/v1.3.1/arrpc-bun-linux-arm64
-            sha512: 51aaf370dd4fe3a60a588ec8caec9c37ef9c686e2414408c5c8558195fa27e97558c2bede4f8aa1f6a1d4549c1ce6a150a566b78ed58ae1d0d496bd9c38288d3
-            dest-filename: arrpc-bun-linux-arm64
-            only-arches: [aarch64]
+      - type: file
+        url: https://github.com/Creationsss/arrpc-bun/releases/download/v1.3.1/arrpc-bun-linux-arm64
+        sha512: 51aaf370dd4fe3a60a588ec8caec9c37ef9c686e2414408c5c8558195fa27e97558c2bede4f8aa1f6a1d4549c1ce6a150a566b78ed58ae1d0d496bd9c38288d3
+        dest-filename: arrpc-bun-linux-arm64
+        only-arches: [aarch64]
